# Generated by Django 4.1.5 on 2023-01-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Персонаж')),
                ('description', models.TextField(verbose_name='Характеристика')),
                ('image', models.ImageField(upload_to='characters/', verbose_name='Изображение')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('unknow', 'неизвестно')], max_length=50, verbose_name='Гендер')),
                ('race', models.CharField(max_length=100, verbose_name='Раса')),
                ('alive', models.CharField(choices=[('alive', 'Живой'), ('death', 'Мертвый'), ('unknow', 'неизвестно')], max_length=50, verbose_name='Статус жизни')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Локация')),
                ('world', models.CharField(max_length=255, verbose_name='Измерение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='location/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Epizod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.PositiveIntegerField(verbose_name='Номер серии')),
                ('number_season', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('image', models.ImageField(upload_to='epizod/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('premiere', models.DateTimeField(verbose_name='Дата')),
                ('characters', models.ManyToManyField(to='mainapp.character', verbose_name='Персонажи')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='birth_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_location', to='mainapp.location', verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='mainapp.location', verbose_name='Место нахождения'),
        ),
    ]
