# Generated by Django 4.1.5 on 2023-01-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_epizod_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epizod',
            name='characters',
            field=models.ManyToManyField(related_name='herois', to='mainapp.character', verbose_name='Персонажи'),
        ),
    ]
